### Send POST request with json body
POST http://localhost:8888/lessons
Content-Type: application/json

{
  "slug": "abcd",
  "title": "React pro začátečníky",
  "description": "Základy Reactu pro začátečníky",
  "heroImage": "",
  "questions": [
    {
      "id": 5,
      "type": "pickOne",
      "question": "Jaký hook použijete pro stav?",
      "answers": [
        {
          "id": 0,
          "text": "useEffect",
          "comments": "Tato volba není správná, protože je ..."
        },
        {
          "id": 1,
          "text": "useState",
          "comments": "Tato volba není správná, protože je ..."
        },
        {
          "id": 2,
          "text": "useContext",
          "comments": "Tato volba není správná, protože je ..."
        },
        {
          "id": 20,
          "text": "useContext",
          "comments": "Tato volba není správná, protože je ..."
        }
      ],
      "correct": 1,
      "comment": "Použije se useEffect"
    }
  ]
}